name: A workflow for my Hello World webside
on: push
jobs:
  build-job:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      name: Check out code
      run: echo Hello World
